from typing import List
from pygen_types import MAbiFunc
from utils import write_if_different


class AbiWriter:
    STUB_COMMENT = "// Movutl autogenerated file (AbiWriter)\n"

    def __init__(self):
        self.funcs: List[MAbiFunc] = []

    def set(self, funcs: List[MAbiFunc]):
        self.funcs = funcs

    def save(self):
        self._write_fields()
        self._write_make_abi()

    def _write_fields(self):
        lines = [self.STUB_COMMENT]
        for f in self.funcs:
            lines.append(f"  {f.ret_type} (*{f.field_name})({f.args}) = nullptr;\n")
        write_if_different("../movutl/generated/generated_abi_fields.inc", "".join(lines))

    def _write_make_abi(self):
        body = (
            self.STUB_COMMENT
            + "#include <movutl/plugin/abi.h>\n"
            + "#include <movutl/plugin/plugin.hpp>\n\n"
            + "namespace mu::detail {\n\n"
            + "ABIContext make_abi() {\n"
            + "  ABIContext abi{};\n"
            + "  abi.abi_version = 1;\n"
        )
        for f in self.funcs:
            body += f"  abi.{f.field_name} = &{f.name};\n"
        body += "  return abi;\n}\n\n} // namespace mu::detail\n"
        write_if_different("../movutl/generated/generated_abi.cpp", body)
