import re
from utils import write_if_different

ICON_DEFINE_RE = re.compile(r'^#define\s+(ICON_\w+)\s+"((?:\\x[0-9a-fA-F]{2}|[^"\\])*)"')


class IconLuaWriter:
    def __init__(self, filename: str):
        self.output_filename = "../lancher/runtime/" + filename
        self.entries: list[tuple[str, str]] = []

    def parse(self, header_file: str):
        with open(header_file) as f:
            for line in f:
                m = ICON_DEFINE_RE.match(line.strip())
                if m:
                    self.entries.append((m.group(1), m.group(2)))

    def save(self):
        lines = ["-- Auto-generated by pygen/IconLuaWriter.py. Do not edit manually.", "return {"]
        for name, raw in self.entries:
            # LuaJIT(Lua5.1構文)は\xNN形式の16進エスケープに非対応なため、10進\dddエスケープへ変換する
            lua_escaped = re.sub(r"\\x([0-9a-fA-F]{2})", lambda m: "\\" + str(int(m.group(1), 16)), raw)
            lines.append(f'  {name} = "{lua_escaped}",')
        lines.append("}")
        write_if_different(self.output_filename, "\n".join(lines) + "\n")
