from pygen_types import MFunction, MEnum, MClass, MArgument, ArgumentType
from typing import List
from utils import logger, write_if_different

# cutil::prop_info_of<T>()特殊化が存在する型のみ対応(cutil組み込み+movutl/core/prop_types.hppのアダプタ)。
SUPPORTED_CTYPES = {
    "bool",
    "int",
    "int32_t",
    "uint8_t",
    "uint32_t",
    "float",
    "std::string",
    "Vec2",
    "Vec3",
    "Vec4",
    "Vec4b",
}


class PropsWriter:
    PREFIX = "props_"
    STUB_COMMENT = "// Movutl autogenerated file (PropsWriter)\n"

    def set(
        self,
        funcs_list: List[MFunction],
        enums_list: List[MEnum],
        classes_list: List[MClass],
    ):
        for c in classes_list:
            self.register_class(c)

    def __init__(self, filename: str):
        self.autogen_text = (
            "#include <cutil/prop.hpp>\n"
            "#include <movutl/app/app.hpp>\n"
            "#include <movutl/asset/entity.hpp>\n"
            "#include <movutl/asset/text.hpp>\n"
            "#include <movutl/asset/image.hpp>\n"
            "#include <movutl/asset/movie.hpp>\n"
            "#include <movutl/asset/audio.hpp>\n"
            "#include <movutl/asset/framebuffer.hpp>\n"
            "#include <movutl/core/anim.hpp>\n"
            "#include <movutl/core/prop_types.hpp>\n"
            "#include <movutl/asset/track.hpp>\n"
            "#include <movutl/asset/composition.hpp>\n"
            "namespace mu { \n"
        )
        self.output_filename = "../movutl/generated/" + filename

    def save(self):
        output = (  #
            self.STUB_COMMENT  #
            + self.autogen_text  #
            + "} // namespace mu\n"  #
        )
        write_if_different(self.output_filename, output)

    def _should_write(self, cls: MClass, funcname: str):
        for f in cls.funcs:
            if f.name == funcname:
                return f.should_autogen
        return False

    def register_class(self, cls: MClass):
        if self._should_write(cls, "getPropsInfo"):
            self._write_getPropsInfo_fn(cls)
        if self._should_write(cls, "getProps"):
            self._write_getProps(cls)
        if self._should_write(cls, "setProps"):
            self._write_setProps(cls)

    def _write_getPropsInfo_fn(self, cls: MClass):
        self.autogen_text += (
            f"const cutil::PropInfo* {cls.name}::getPropsInfo() const {{\n"
            f"  static const cutil::PropInfo info = [] {{\n"
            f"    cutil::PropInfo p;\n"
        )
        for prop in cls.props:
            if prop.c_type not in SUPPORTED_CTYPES:
                self.autogen_text += f"    // {prop.name} has an unsupported type ({prop.c_type})\n"
                continue
            self.autogen_text += (
                f'    p.fields.push_back(cutil::PropInfo::Field("{prop.name}", '
                f"offsetof({cls.name}, {prop.name}), cutil::prop_info_of<{prop.c_type}>()));\n"
            )
            if prop.dispname != "":
                self.autogen_text += f'    p.fields.back().set_label("{prop.dispname}");\n'
            if prop.desc != "":
                self.autogen_text += f'    p.fields.back().set_desc("{prop.desc}");\n'
            if prop.minvalue != "":
                self.autogen_text += f"    p.fields.back().min_value = {prop.minvalue};\n"
            if prop.maxvalue != "":
                self.autogen_text += f"    p.fields.back().max_value = {prop.maxvalue};\n"
            if prop.step != "":
                self.autogen_text += f"    p.fields.back().drag_speed = {prop.step};\n"
            if prop.readonly:
                self.autogen_text += "    p.fields.back().flags = p.fields.back().flags | cutil::PropFlags::ReadOnly;\n"
        self.autogen_text += "    return p;\n  }();\n  return &info;\n}\n"

    def _write_getProps(self, cls: MClass):
        self.autogen_text += (
            f"cutil::Prop {cls.name}::getProps() const {{\n"
            f"  cutil::Prop p;\n"
            f"  p.dump(this, getPropsInfo());\n"
            f"  return p;\n}}\n"
        )

    def _write_setProps(self, cls: MClass):
        self.autogen_text += (
            f"void {cls.name}::setProps(const cutil::Prop& p) {{\n"
            f"  (void)p.load_to(this, getPropsInfo());\n}}\n"
        )
